// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8FdR6U_h3gNt--PMZBDWbrC6VvrUMB6o',
    appId: '1:294319668906:web:13d80454057cb95abb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    authDomain: 'kpop-3b0b6.firebaseapp.com',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    measurementId: 'G-JHDHQ25B6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYsiiLyZNhWxntmYEKHcHAA6-7a5QQ98',
    appId: '1:294319668906:android:0d427a7995188cb7bb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsM_x3oQVUSNB3S3SVxQV32B329k9fTnI',
    appId: '1:294319668906:ios:f0772a354eee8b6abb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    androidClientId: '294319668906-ulr9k3tmgdnh855f0jc9m95mrhfc5v37.apps.googleusercontent.com',
    iosClientId: '294319668906-kdptm91i25bmmi3ucsdj0f7njc4hlihb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsM_x3oQVUSNB3S3SVxQV32B329k9fTnI',
    appId: '1:294319668906:ios:f0772a354eee8b6abb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    androidClientId: '294319668906-ulr9k3tmgdnh855f0jc9m95mrhfc5v37.apps.googleusercontent.com',
    iosClientId: '294319668906-kdptm91i25bmmi3ucsdj0f7njc4hlihb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8FdR6U_h3gNt--PMZBDWbrC6VvrUMB6o',
    appId: '1:294319668906:web:ef3f1e555ad742c3bb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    authDomain: 'kpop-3b0b6.firebaseapp.com',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    measurementId: 'G-RJ9TB4KGLY',
  );

}